language: node_js
node_js: node
deploy: 
  provider : pages
  skip-cleanup : true
  github-token :  $GITHUB_TOKEN
  keep-history : true
  local-dir : out
  on : 
     branch: master

script: 
  - npm test

before_deploy: 
  - node_modules/.bin/jsdoc src